name: ddd_clean_template # Your application name
organization_domain: uz.digitagro # Your organization domain
description: "A new Flutter project." # Your application description
publish_to: 'none'
version: 1.0.0+1 # Your application version

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  alice: ^1.0.0
  alice_dio: ^1.0.7
  animated_flip_counter: ^0.3.4
  auto_route: ^10.2.0
  bloc: ^9.1.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  easy_localization: ^3.0.8
  flutter_bloc: ^9.1.0
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.4.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  freezed_annotation: ^3.0.0
  get_it: ^8.2.0
  google_fonts: ^6.3.2
  hive_ce: ^2.15.1
  http_cache_hive_store: ^5.0.1
  image_picker: ^1.2.0 # Should add configuration to android and ios
  injectable: ^2.5.2
  internet_connection_checker_plus: ^2.9.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.4
  pull_to_refresh: ^2.0.0
  safe_device: ^1.3.8
  shimmer: ^3.0.0
  sqflite: ^2.4.2
  url_launcher: ^6.3.2 # Should add configuration to android and ios
  webview_flutter: ^4.13.0
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.10.1
  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  injectable_generator: ^2.9.0
  prompt_generator: ^1.0.1
  res_generator: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/tr/