name: ddd_clean_template # Your application name, remove comment
organization_domain: uz.digitagro # Your organization domain, remove comment
description: "A new Flutter project." # Your application description, remove comment
publish_to: 'none'
version: 1.0.0+1 # Your application version, remove comment

environment:
  sdk: ^3.9.0

dependencies:
  alice: ^1.0.0
  alice_dio: ^1.0.7
  animated_flip_counter: ^0.3.4
  auto_route: ^11.1.0
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  dio_cache_interceptor: ^4.0.5
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.4.0
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  fluttertoast: ^9.0.0
  freezed_annotation: ^3.0.0
  get_it: ^9.2.0
  google_fonts: ^6.3.3
  hive_ce: ^2.16.0
  http_cache_hive_store: ^5.0.1
  image_cropper: ^11.0.0 # Should add configuration to android and ios, remove comment
  image_picker: ^1.2.1 # Should add configuration to android and ios, remove comment
  injectable: ^2.7.1+4
  internet_connection_checker_plus: ^2.9.1+2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.1
  path: ^1.9.1
  path_provider: ^2.1.4
  pull_to_refresh: ^2.0.0
  safe_device: ^1.3.8
  shimmer: ^3.0.0
  skeletonizer: ^2.1.2
  sqflite: ^2.4.2
  url_launcher: ^6.3.2 # Should add configuration to android and ios, remove comment
  webview_flutter: ^4.13.0
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7 # if you want, you can remove this line and above configs
  freezed: ^3.2.4
  icons_launcher: ^3.0.3 # if you want, you can remove this line and above configs
  injectable_generator: ^2.12.0
  json_serializable: ^6.11.3
  prompt_generator: ^1.1.3
  res_generator: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/tr/

flutter_native_splash:
  background_image: assets/images/splash.png
  fullscreen: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/app_icon.png
    icon_background_color: "#FFFFFF"

icons_launcher:
  image_path: "assets/images/app_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true